name: Schedule AdBlock Rule Generator

on:
  schedule:
    - cron: '*/20 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # 手动实现 checkout
    - name: Checkout repository
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.ref }}

    - name: Install PowerShell
      run: |
        choco install powershell-core -y

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        pwsh ./adblock_rule_generator.ps1

    - name: Commit and Push YAML file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add adblock_reject.yaml
        git commit -m "Update adblock_reject.yaml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Error Handling
      if: failure()
      run: |
        echo "Workflow failed. Please check the logs for more information."
        echo "Current directory contents:"
        ls -R
        echo "Git status:"
        git status
