# 工作流的名称，会显示在GitHub Actions标签页中
name: Schedule AdBlock Rule Generator

# 定义触发工作流的事件
on:
  # 使用cron表达式设置定时触发
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  # 当有推送到main分支时也触发工作流
  push:
    branches:
      - main

# 定义工作流中的作业
jobs:
  # 定义一个名为"build"的作业
  build:
    # 指定作业运行的环境为最新版本的Windows
    runs-on: windows-latest
    
    # 定义作业的步骤
    steps:
    # 步骤1：检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v2  # 使用官方的checkout action

    # 步骤2：安装PowerShell Core
    - name: Install PowerShell
      run: |
        choco install powershell-core -y  # 使用Chocolatey包管理器安装PowerShell Core

    # 步骤3：运行PowerShell脚本
    - name: Run PowerShell Script
      shell: pwsh  # 指定使用PowerShell Core运行
      run: |
        pwsh ./adblock_rule_generator.ps1  # 运行广告拦截规则生成脚本

    # 步骤4：提交并推送生成的YAML文件
    - name: Commit and Push YAML file
      run: |
        # 配置Git用户名和邮箱（使用GitHub Actions作为作者）
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        # 将生成的YAML文件添加到Git
        git add adblock_reject.yaml
        # 创建一个新的提交
        git commit -m "Update adblock_reject.yaml"
        # 推送更改到仓库
        git push
      # 设置环境变量，提供GitHub Token用于认证
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
