name: Run AdBlock Rule Generator

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run adblock_rule_generator.ps1
      run: pwsh ./adblock_rule_generator.ps1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
