name: Convert YAML to MRS

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U git+https://github.com/KT-Yeh/mihomo.git

      - name: Verify mihomo installation
        run: |
          which mihomo
          mihomo --version

      - name: Run conversion script
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python convert_yaml_to_mrs.py
