# 步骤4：提交并推送更改（包括 mihomo.exe 和标记文件）
      - name: Push changes
        shell: powershell
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # 配置 Git 用户信息
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          # 拉取最新更改
          git pull https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} --rebase
          
          # 添加转换后的文件和 mihomo.exe 以及标记文件到 Git
          git add adblock_reject.mrs mihomo.exe .mihomo_downloaded
          
          # 检查是否有更改需要提交
          $changes = git status --porcelain
          if ($changes) {
            # 如果有更改，进行提交
            git commit -m "Update adblock_reject.mrs and add mihomo.exe"
            
            # 推送更改，包含重试机制
            $maxAttempts = 5
            $attempt = 1
            do {
              try {
                Write-Host "Attempting to push changes (Attempt $attempt of $maxAttempts)..."
                git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
                Write-Host "Changes successfully pushed."
                break
              }
              catch {
                if ($attempt -eq $maxAttempts) {
                  Write-Host "Failed to push changes after $maxAttempts attempts. Error: $_"
                  exit 1
                }
                Write-Host "Push attempt $attempt failed. Retrying in 30 seconds..."
                $attempt++
                Start-Sleep -Seconds 30
              }
            } while ($attempt -le $maxAttempts)
          } else {
            Write-Host "No changes to commit."
          }
