name: Convert Adblock Rules

on:
  workflow_dispatch:
  push:
    paths:
      - 'adblock_reject.txt'

jobs:
  convert-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if mihomo exists
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/mihomo" ]; then
            echo "Error: mihomo file not found in the root directory"
            exit 1
          fi

      - name: Set execute permissions for mihomo
        run: chmod +x $GITHUB_WORKSPACE/mihomo

      - name: Display mihomo version and contents of current directory
        run: |
          $GITHUB_WORKSPACE/mihomo -v || echo "Failed to get mihomo version"
          ls -la $GITHUB_WORKSPACE

      - name: Convert ruleset
        run: |
          $GITHUB_WORKSPACE/mihomo convert-ruleset domain yaml $GITHUB_WORKSPACE/adblock_reject.txt $GITHUB_WORKSPACE/adblock_reject.mrs
        working-directory: $GITHUB_WORKSPACE

      - name: Check conversion result
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/adblock_reject.mrs" ]; then
            echo "Error: adblock_reject.mrs was not created. Conversion likely failed."
            exit 1
          fi

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add adblock_reject.mrs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update adblock_reject.mrs in root directory" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
