name: Convert Adblock Rules  # 工作流名称

on:
  schedule:
    - cron: '*/20 * * * *'  # 每 20 分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流
  push:
    paths:
      - 'adblock_reject.txt'  # 当 adblock_reject.txt 文件被推送时触发

jobs:
  convert-ruleset:  # 任务名称
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境
    steps:
      - name: Checkout repository  # 检出仓库
        uses: actions/checkout@v2  # 使用 checkout 动作版本2

      - name: Check if mihomo exists  # 检查 mihomo 文件是否存在
        run: |
          if [ -f "$GITHUB_WORKSPACE/mihomo" ]; then
            echo "mihomo already exists. Skipping download."  # 如果存在，输出信息并跳过下载
            exit 0  # 退出步骤

      - name: Download latest Mihomo release  # 下载最新的 Mihomo 版本
        if: steps.checkout.outputs.mihomo-exists != 'true'  # 如果 mihomo 不存在则执行
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r .tag_name)  # 获取最新发布的版本号
          curl -L -o mihomo "https://github.com/MetaCubeX/mihomo/releases/download/${LATEST_RELEASE}/mihomo-linux-amd64-${LATEST_RELEASE}"  # 下载 mihomo 可执行文件
          chmod +x mihomo  # 赋予可执行权限

      - name: Verify mihomo download  # 验证 mihomo 下载是否成功
        if: steps.checkout.outputs.mihomo-exists != 'true'  # 如果 mihomo 不存在则执行
        run: file mihomo  # 显示 mihomo 文件信息

      - name: Commit and push mihomo  # 提交并推送 mihomo 文件
        if: steps.checkout.outputs.mihomo-exists != 'true'  # 如果 mihomo 不存在则执行
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # 配置提交用户的邮箱
          git config --global user.name "github-actions[bot]"  # 配置提交用户的名称
          git add mihomo  # 添加 mihomo 文件到 Git 暂存区
          git commit -m "Add mihomo executable"  # 提交更改，备注信息为 "Add mihomo executable"
          git push  # 推送到远程仓库

      - name: Ensure mihomo is executable  # 确保 mihomo 文件可执行
        run: chmod +x $GITHUB_WORKSPACE/mihomo  # 赋予可执行权限

      - name: Display mihomo version and contents of current directory  # 显示 mihomo 版本和当前目录内容
        run: |
          echo "Checking file type:"  # 输出信息
          file $GITHUB_WORKSPACE/mihomo  # 显示 mihomo 文件类型
          echo "Displaying first 10 lines of mihomo:"  # 输出信息
          head -n 10 $GITHUB_WORKSPACE/mihomo  # 显示 mihomo 文件的前 10 行
          echo "Getting mihomo version:"  # 输出信息
          $GITHUB_WORKSPACE/mihomo -v || echo "Failed to get mihomo version"  # 获取 mihomo 版本，如果失败则输出错误信息
          echo "Listing contents of workspace:"  # 输出信息
          ls -l $GITHUB_WORKSPACE  # 列出工作目录的内容

      - name: Convert Adblock Rules  # 转换 Adblock 规则
        run: |
          $GITHUB_WORKSPACE/mihomo convert-ruleset domain/ipcidr yaml adblock_reject.yaml adblock_reject.mrs  # 使用 mihomo 转换规则
          
      - name: Commit and push converted rules  # 提交并推送转换后的规则文件
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # 配置提交用户的邮箱
          git config --global user.name "github-actions[bot]"  # 配置提交用户的名称
          git add adblock_reject.mrs  # 添加转换后的规则文件到 Git 暂存区
          git commit -m "Update adblock_reject.mrs"  # 提交更改，备注信息为 "Update adblock_reject.mrs"
          git push  # 推送到远程仓库
