name: Convert YAML to MRS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install mihomo
      run: |
        go install github.com/MetaCubeX/mihomo/dev@latest

    - name: Convert YAML to MRS
      run: |
        for file in *.yaml; do
          mihomo convert-ruleset domain/ipcidr yaml "$file" "${file%.yaml}.mrs"
        done

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.mrs
        git commit -m "Convert YAML to MRS" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
