name: Convert Adblock Rules

on:
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'adblock_reject.txt'  # 当adblock_reject.txt文件变更时触发

jobs:
  convert-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions for mihomo
        run: chmod +x ./mihomo

      - name: Convert ruleset
        run: |
          ./mihomo convert-ruleset domain yaml adblock_reject.txt adblock_reject.mrs

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add adblock_reject.mrs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update adblock_reject.mrs in root directory" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
