name: mihomo Conversion Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual execution'

jobs:
  convert-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install mihomo
      run: |
        pip install -U git+https://github.com/KT-Yeh/mihomo.git

    - name: Convert YAML files
      run: |
        for file in *.yaml; do
          if [ -f "$file" ]; then
            mihomo convert-ruleset domain/ipcidr yaml "$file" "${file%.yaml}.mrs"
          fi
        done

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.mrs
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update .mrs files" && git push)

    - name: Output trigger reason
      if: github.event_name == 'workflow_dispatch'
      run: echo "Workflow manually triggered. Reason: ${{ github.event.inputs.reason }}"
