name: Convert YAML to MRS

on:
  push:
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Convert YAML to MRS
        run: |
          python - <<EOF
          import yaml
          import struct
          import os

          def encode_value(value):
              if isinstance(value, (str, int, float, bool)):
                  return str(value).encode('utf-8')
              elif isinstance(value, list):
                  return ','.join(map(str, value)).encode('utf-8')
              elif isinstance(value, dict):
                  return yaml.dump(value).encode('utf-8')
              else:
                  return str(value).encode('utf-8')

          def yaml_to_mrs(yaml_file, mrs_file):
              with open(yaml_file, 'r') as f:
                  data = yaml.safe_load(f)
              
              with open(mrs_file, 'wb') as f:
                  f.write(b'MRS\0')
                  
                  def write_data(d):
                      if isinstance(d, dict):
                          for key, value in d.items():
                              key_bytes = key.encode('utf-8')
                              value_bytes = encode_value(value)
                              f.write(struct.pack('<I', len(key_bytes)))
                              f.write(key_bytes)
                              f.write(struct.pack('<I', len(value_bytes)))
                              f.write(value_bytes)
                      elif isinstance(d, list):
                          for item in d:
                              write_data(item)
                  
                  write_data(data)

          for file in os.listdir('.'):
              if file.endswith('.yaml'):
                  yaml_to_mrs(file, file[:-5] + '.mrs')
                  print(f"Converted {file} to {file[:-5]}.mrs")
          EOF

      - name: Push MRS files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.mrs
          git commit -m "Convert YAML to MRS using Python" || echo "No changes to commit"
          git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

      - name: Push to root directory
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout ${{ github.ref }}
          mv *.mrs ./ 2>/dev/null || true
          git add *.mrs
          git commit -m "Move MRS files to root directory" || echo "No changes to commit"
          git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
