name: Convert Adblock Rules

on:
  workflow_dispatch:
  push:
    paths:
      - 'adblock_reject.txt'

jobs:
  convert-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if mihomo exists
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/mihomo" ]; then
            echo "Error: mihomo file not found in the root directory"
            exit 1
          fi

      - name: Set execute permissions for mihomo
        run: chmod +x $GITHUB_WORKSPACE/mihomo

      - name: Display mihomo version and contents of current directory
        run: |
          $GITHUB_WORKSPACE/mihomo -v || echo "Failed to get mihomo version"
          ls -la $GITHUB_WORKSPACE

      - name: Convert ruleset
        run: |
          ./mihomo convert-ruleset domain yaml adblock_reject.txt adblock_reject.mrs

      - name: Check conversion result
        run: |
          if [ ! -f "adblock_reject.mrs" ]; then
            echo "Error: Conversion failed, adblock_reject.mrs not found"
            exit 1
          else
            echo "Conversion successful, adblock_reject.mrs created"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add adblock_reject.mrs
          git commit -m "Update adblock_reject.mrs"
          git push
