name: Convert Adblock Rules

on:
  schedule:
    - cron: '*/20 * * * *'  # 每 20 分钟运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'adblock_reject.txt'

jobs:
  convert-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if mihomo exists
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/mihomo" ]; then
            echo "Error: mihomo file not found in the root directory"
            exit 1
          fi

      - name: Ensure mihomo is executable
        run: chmod +x $GITHUB_WORKSPACE/mihomo

      - name: Display mihomo version and contents of current directory
        run: |
          echo "Checking file type:"
          file $GITHUB_WORKSPACE/mihomo
          echo "Displaying first 10 lines of mihomo:"
          head -n 10 $GITHUB_WORKSPACE/mihomo
          echo "Getting mihomo version:"
          $GITHUB_WORKSPACE/mihomo -v || echo "Failed to get mihomo version"
          echo "Listing contents of workspace:"
          ls -la $GITHUB_WORKSPACE

      - name: Convert ruleset
        run: |
          cd $GITHUB_WORKSPACE
          echo "Starting conversion:"
          ./mihomo convert-ruleset domain yaml adblock_reject.txt adblock_reject.mrs
          RESULT=$?
          if [ $RESULT -ne 0 ]; then
            echo "Error: Conversion command failed with exit code $RESULT"
            exit $RESULT
          fi

      - name: Check conversion result
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/adblock_reject.mrs" ]; then
            echo "Error: Conversion failed, adblock_reject.mrs not found"
            exit 1
          else
            echo "Conversion successful, adblock_reject.mrs created"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add adblock_reject.mrs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update adblock_reject.mrs" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
