name: Convert and Commit adblock_reject.mrs

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  convert_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install mihomo
      run: |
        pip install mihomo  # 确保 mihomo 可以通过 pip 安装，如果不行的话，根据实际情况修改

    - name: Convert adblock_reject.txt to adblock_reject.mrs
      run: |
        mihomo convert-ruleset domain yaml adblock_reject.txt adblock_reject.mrs

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add adblock_reject.mrs
        git commit -m 'Update adblock_reject.mrs'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
