name: Convert Specific YAML to MRS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install mihomo
      run: |
        pip install -U git+https://github.com/KT-Yeh/mihomo.git
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Convert YAML to MRS
      run: |
        mihomo convert-ruleset domain/ipcidr yaml adblock.reject.yaml adblock.reject.mrs
        echo "Converted adblock.reject.yaml to adblock.reject.mrs"
        
        mihomo convert-ruleset domain/ipcidr yaml adblock.reject_change.yaml adblock.reject_change.mrs
        echo "Converted adblock.reject_change.yaml to adblock.reject_change.mrs"

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add adblock.reject.mrs adblock.reject_change.mrs
        git commit -m "Convert specific YAML files to MRS" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
