name: Convert Ruleset with Mihomo

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  convert_and_commit:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure mihomo is executable
      run: |
        icacls mihomo.exe /grant Everyone:F

    - name: Convert adblock_reject_change.txt to adblock_reject_change.mrs
      run: |
        .\mihomo.exe convert-ruleset domain yaml adblock_reject_change.txt adblock_reject_change.mrs

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add adblock_reject_change.mrs
        git commit -m 'Update adblock_reject_change.mrs'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
