name: Convert Rulesets with Mihomo

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  convert-rulesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check mihomo and input files
        id: check_files
        run: |
          if [ ! -f "mihomo" ]; then
            echo "MIHOMO_EXISTS=false" >> $GITHUB_OUTPUT
            echo "Error: mihomo executable not found in the repository root."
            exit 1
          fi
          
          for file in adblock_reject.txt adblock_reject_change.txt; do
            if [ ! -f "$file" ]; then
              echo "Error: $file not found in the repository root."
              exit 1
            fi
            if [ ! -s "$file" ]; then
              echo "Error: $file is empty."
              exit 1
            fi
          done

      - name: Execute mihomo commands
        run: |
          ./mihomo convert-ruleset domain yaml adblock_reject.txt adblock_reject.mrs
          ./mihomo convert-ruleset domain yaml adblock_reject_change.txt adblock_reject_change.mrs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add adblock_reject.mrs adblock_reject_change.mrs
          git commit -m "Update mrs files"
          git push
