name: Download Latest Mihomo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行

jobs:
  check-and-download-mihomo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest mihomo release
        id: get_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r .tag_name)
          echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_OUTPUT

      - name: Check current mihomo version
        id: check_version
        run: |
          if [ -f "mihomo" ]; then
            CURRENT_VERSION=$(./mihomo -v | awk '{print $2}')
            echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
            if [ "${{ steps.get_release.outputs.LATEST_RELEASE }}" = "${CURRENT_VERSION}" ]; then
              echo "UPDATE_NEEDED=false" >> $GITHUB_OUTPUT
            else
              echo "UPDATE_NEEDED=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "UPDATE_NEEDED=true" >> $GITHUB_OUTPUT
          fi

      - name: Download mihomo
        if: steps.check_version.outputs.UPDATE_NEEDED == 'true'
        run: |
          DOWNLOAD_URL="https://github.com/MetaCubeX/mihomo/releases/download/${{ steps.get_release.outputs.LATEST_RELEASE }}/mihomo-linux-amd64-${{ steps.get_release.outputs.LATEST_RELEASE }}.gz"
          curl -L -o mihomo.gz $DOWNLOAD_URL
          gunzip mihomo.gz
          chmod +x mihomo

      - name: Commit and push if changed
        if: steps.check_version.outputs.UPDATE_NEEDED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mihomo
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update mihomo to ${{ steps.get_release.outputs.LATEST_RELEASE }}" && git push)

      - name: No update needed
        if: steps.check_version.outputs.UPDATE_NEEDED == 'false'
        run: echo "mihomo is already up to date. No action taken."
