name: Download Mihomo  # 工作流名称

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  download-mihomo:  # 任务名称
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境
    steps:
      - name: Checkout repository  # 检出仓库
        uses: actions/checkout@v2  # 使用 checkout 动作版本2

      - name: Check if mihomo exists  # 检查 mihomo 文件是否存在
        run: |
          if [ -f "$GITHUB_WORKSPACE/mihomo" ]; then
            echo "mihomo already exists. Skipping download."  # 如果存在，输出信息并跳过下载
            exit 0  # 退出步骤

      - name: Download latest Mihomo release  # 下载最新的 Mihomo 版本
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r .tag_name)  # 获取最新发布的版本号
          curl -L -o mihomo "https://github.com/MetaCubeX/mihomo/releases/download/${LATEST_RELEASE}/mihomo-linux-amd64-${LATEST_RELEASE}"  # 下载 mihomo 可执行文件
          chmod +x mihomo  # 赋予可执行权限

      - name: Verify mihomo download  # 验证 mihomo 下载是否成功
        run: |
          file mihomo  # 显示 mihomo 文件信息

      - name: Commit and push mihomo  # 提交并推送 mihomo 文件
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # 配置提交用户的邮箱
          git config --global user.name "github-actions[bot]"  # 配置提交用户的名称
          git add mihomo  # 添加 mihomo 文件到 Git 暂存区
          git commit -m "Add mihomo executable"  # 提交更改，备注信息为 "Add mihomo executable"
          git push  # 推送到远程仓库
