name: Generate Matcher Ruleset entries  # 工作流名称

on:
  push:
    branches: [main]  # 在推送到 main 分支时触发
  pull_request:
    branches: [main]  # 在 pull request 针对 main 分支时触发
  workflow_dispatch:  # 允许手动触发工作流
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟触发一次

jobs:
  process-files:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本作为运行环境
    steps:
    - uses: actions/checkout@v2  # 使用官方的 checkout 操作来检出代码

    - name: Process adblock_reject.txt  # 处理 adblock_reject.txt 文件
      run: |
        # 找到并处理 payload 列表部分，去掉表头并在每行末尾添加 ",REJECT"
        awk '/^payload:/{flag=1; next} /:/{flag=0} flag' adblock_reject.txt | sed 's/$/,REJECT/' | sed 's/^[[:space:]]*//' > adblock_reject_change.txt

    - name: Process adblock_reject.yaml  # 处理 adblock_reject.yaml 文件
      run: |
        # 找到并处理 payload 列表部分，去掉表头并在每行末尾添加
