name: Generate Matcher Ruleset entries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Process adblock_reject.txt
      run: |
        sed -n '/^#/p; /^- DOMAIN,/p' adblock_reject.txt | sed '/^- DOMAIN,/s/$/, REJECT/' > adblock_reject_change.txt

    - name: Process adblock_reject.yaml
      run: |
        sed -n '/^#/p; /^- DOMAIN,/p' adblock_reject.yaml | sed '/^- DOMAIN,/s/$/, REJECT/' > adblock_reject_change.yaml

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add adblock_reject_change.txt adblock_reject_change.yaml
        git commit -m "Process adblock files: keep comments and DOMAIN lines, add REJECT" || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
