name: Generate Matcher Ruleset entries  # 工作流名称

on:
  push:
    branches: [main]  # 在推送到 main 分支时触发
  pull_request:
    branches: [main]  # 在 pull request 针对 main 分支时触发
  workflow_dispatch:  # 允许手动触发工作流
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟触发一次

jobs:
  process-files:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本作为运行环境
    steps:
    - uses: actions/checkout@v2  # 使用官方的 checkout 操作来检出代码

    - name: Process adblock_reject.txt  # 处理 adblock_reject.txt 文件
      run: |
        # 跳过注释行（以 "#" 开头的行），在每行末尾添加 ",REJECT"，去除行首空白字符，保存为新文件
        grep -v '^#' adblock_reject.txt | sed 's/^[[:space:]]*//; s/$/,REJECT/' > adblock_reject_change.txt

    - name: Process adblock_reject.yaml  # 处理 adblock_reject.yaml 文件
      run: |
        # 跳过注释行（以 "#" 开头的行），在每行末尾添加 ",REJECT"，去除行首空白字符，保存为新文件
        grep -v '^#' adblock_reject.yaml | sed 's/^[[:space:]]*//; s/$/,REJECT/' > adblock_reject_change.yaml

    - name: Commit changes  # 提交更改
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用存储在仓库中的 TOKEN 密钥
      run: |
        # 配置 Git 用户信息
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        # 添加更改的文件并提交
        git add adblock_reject_change.txt adblock_reject_change.yaml
        git commit -m "Processed adblock_reject files"
        # 设置远程仓库 URL，使用 TOKEN 进行身份验证
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        # 推送更改到远程仓库
        git push origin main
