name: Run Workflows Sequentially

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  run_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger and Wait for AdBlock Rule Generator YAML
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_YAML.yml"
          run_id=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d '{"ref":"main"}' | jq -r '.id')
          echo "Triggered workflow $workflow_id with run ID $run_id"
          while [ "$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 10
          done
          conclusion=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi

      # Repeat the above step for each workflow in your sequence
