# 工作流名称
name: Combined AdBlock Rule Generation

# 触发条件：可以手动触发，或者每20分钟自动运行一次
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次

# 定义作业
jobs:
  generate_rules:
    runs-on: ubuntu-latest  # 在最新版本的Ubuntu上运行
    steps:
      # 步骤1：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤2：设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用最新的Python 3版本

      # 步骤3：安装必要的Python依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml  # 安装脚本所需的包

      # 步骤4：生成AdBlock规则（YAML和TXT格式）
      - name: Generate AdBlock Rules (YAML and TXT)
        run: |
          python scripts/adblock_rule_generator.py --format yaml
          python scripts/adblock_rule_generator.py --format txt

      # 步骤5：将YAML格式的规则集转换为MRS格式
      - name: Convert Ruleset YAML to MRS
        run: python scripts/convert_yaml_to_mrs.py

      # 步骤6：生成CLASH和SURGE格式的Matcher Ruleset条目
      - name: Generate Matcher Ruleset entries (CLASH and SURGE)
        run: |
          python scripts/generate_matcher_entries.py --format clash
          python scripts/generate_matcher_entries.py --format surge

      # 步骤7：准备发布文件
      - name: Prepare Release Files
        run: |
          mkdir -p release  # 创建release目录
          # 复制所有生成的文件到release目录
          cp output/*.yaml release/
          cp output/*.txt release/
          cp output/*.mrs release/
          cp output/*_clash.yaml release/
          cp output/*_surge.list release/

      # 步骤8：创建GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*  # 上传release目录中的所有文件
          name: AdBlock Rules Update ${{ github.run_number }}  # 使用运行次数作为版本号
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行认证

      # 步骤9：更新仓库
      - name: Update Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .  # 添加所有更改
          git commit -m "Update AdBlock rules [skip ci]"  # 提交更改，并跳过CI
          git push  # 推送更改到仓库
