name: Run Workflows Sequentially

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  run_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run AdBlock Rule Generator YAML
        uses: ./.github/actions/trigger-and-wait-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Run_AdBlock_Rule_Generator_YAML.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Run AdBlock Rule Generator TXT
        uses: ./.github/actions/trigger-and-wait-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Run_AdBlock_Rule_Generator_TXT.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Convert Ruleset YAML to MRS
        uses: ./.github/actions/trigger-and-wait-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Convert_Ruleset_YAML_to_MRS.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Generate Matcher Ruleset entries (CLASH)
        uses: ./.github/actions/trigger-and-wait-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Generate_Matcher_Ruleset_entries_CLASH.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Generate Matcher Ruleset entries (SURGE)
        uses: ./.github/actions/trigger-and-wait-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Generate_Matcher_Ruleset_entries_SURGE.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Release Adblock file
        uses: ./.github/actions/trigger-and-wait-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Release_Adblock_file.yml
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
