name: Run Workflows Sequentially

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次

jobs:
  run_workflows:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Run AdBlock Rule Generator YAML
      - name: Run AdBlock Rule Generator YAML
        uses: ./.github/actions/trigger-and-wait-action.yml
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Run_AdBlock_Rule_Generator_YAML.yml
          wait_interval: 10

      # Step 2: Run AdBlock Rule Generator TXT
      - name: Run AdBlock Rule Generator TXT
        uses: ./.github/actions/trigger-and-wait-action.yml
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Run_AdBlock_Rule_Generator_TXT.yml
          wait_interval: 10

      # Step 3: Convert Ruleset YAML to MRS
      - name: Convert Ruleset YAML to MRS
        uses: ./.github/actions/trigger-and-wait-action.yml
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Convert_Ruleset_YAML_to_MRS.yml
          wait_interval: 10

      # Step 4: Generate Matcher Ruleset entries (CLASH)
      - name: Generate Matcher Ruleset entries (CLASH)
        uses: ./.github/actions/trigger-and-wait-action.yml
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Generate_Matcher_Ruleset_entries_CLASH.yml
          wait_interval: 10

      # Step 5: Generate Matcher Ruleset entries (SURGE)
      - name: Generate Matcher Ruleset entries (SURGE)
        uses: ./.github/actions/trigger-and-wait-action.yml
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Generate_Matcher_Ruleset_entries_SURGE.yml
          wait_interval: 10

      # Step 6: Release Adblock file
      - name: Release Adblock file
        uses: ./.github/actions/trigger-and-wait-action.yml
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.TOKEN }}
          workflow_file_name: Release_ADblock_file.yml
          wait_interval: 10
