name: Run Workflows Sequentially

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  run_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger and wait for Run_AdBlock_Rule_Generator_YAML
        id: run_adblock_rule_generator_yaml
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_YAML.yml"
          ref="main"
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id"

          run_id=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/runs?branch=$ref&status=in_progress" | jq -r '.workflow_runs[0].id')
          echo "Run ID: $run_id"
          while [ "$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 2
          done
          conclusion=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi

      - name: Trigger and wait for Run_AdBlock_Rule_Generator_TXT
        id: run_adblock_rule_generator_txt
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Run_AdBlock_Rule_Generator_TXT.yml"
          ref="main"
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id"

          run_id=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/runs?branch=$ref&status=in_progress" | jq -r '.workflow_runs[0].id')
          echo "Run ID: $run_id"
          while [ "$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 2
          done
          conclusion=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi

      - name: Trigger and wait for Convert_Ruleset_YAML_to_MRS
        id: convert_ruleset_yaml_to_mrs
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Convert_Ruleset_YAML_to_MRS.yml"
          ref="main"
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id"

          run_id=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/runs?branch=$ref&status=in_progress" | jq -r '.workflow_runs[0].id')
          echo "Run ID: $run_id"
          while [ "$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 2
          done
          conclusion=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi

      - name: Trigger and wait for Generate_Matcher_Ruleset_entries_CLASH
        id: generate_matcher_ruleset_entries_clash
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Generate_Matcher_Ruleset_entries_CLASH.yml"
          ref="main"
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id"

          run_id=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/runs?branch=$ref&status=in_progress" | jq -r '.workflow_runs[0].id')
          echo "Run ID: $run_id"
          while [ "$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 2
          done
          conclusion=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi

      - name: Trigger and wait for Generate_Matcher_Ruleset_entries_SURGE
        id: generate_matcher_ruleset_entries_surge
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Generate_Matcher_Ruleset_entries_SURGE.yml"
          ref="main"
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id"

          run_id=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/runs?branch=$ref&status=in_progress" | jq -r '.workflow_runs[0].id')
          echo "Run ID: $run_id"
          while [ "$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 2
          done
          conclusion=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi

      - name: Trigger and wait for Release_Adblock_file
        id: release_adblock_file
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          workflow_id="Release_Adblock_file.yml"
          ref="main"
          response=$(curl -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
            -d "{\"ref\":\"$ref\"}")
          echo "Triggered workflow $workflow_id"

          run_id=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/runs?branch=$ref&status=in_progress" | jq -r '.workflow_runs[0].id')
          echo "Run ID: $run_id"
          while [ "$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.status')" != "completed" ]; do
            echo "Waiting for workflow $workflow_id to complete..."
            sleep 2
          done
          conclusion=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs/$run_id" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow $workflow_id failed with conclusion $conclusion"
            exit 1
          fi
