name: Process adblock files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Process adblock_reject.txt
      run: |
        tail -n +2 adblock_reject.txt | sed 's/$/,REJECT/' | sed 's/^[[:space:]]*//' > adblock_reject_change.txt

    - name: Process adblock_reject.yaml
      run: |
        tail -n +2 adblock_reject.yaml | sed 's/$/,REJECT/' | sed 's/^[[:space:]]*//' > adblock_reject_change.yaml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add adblock_reject_change.txt adblock_reject_change.yaml
        git commit -m "Process adblock files: remove first line, add REJECT, left align" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
