name: Release ADblock file  # 工作流名称
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          tag_name: release-${{ env.time }}  # 使用当前时间作为标签名称
          release_name: Release ${{ env.time }}  # 使用当前时间作为发布名称
          body: "Periodic release of adblock files."  # 发布说明
          draft: false  # 发布为正式版本
          prerelease: false  # 不发布为预发布版本




      - name: Upload adblock_reject.mrs  # 上传adblock_reject.mrs文件
        uses: actions/upload-release-asset@v1  # 使用官方的upload-release-asset操作来上传发布资源
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布版本步骤中的上传URL
          asset_path: adblock_reject.mrs  # 要上传的文件路径
          asset_name: adblock_reject.mrs  # 上传后的文件名称
          asset_content_type: application/x-yaml  # 文件的内容类型





	   - name: Upload adblock_reject.srs  # 上传adblock_reject.srs文件
        uses: actions/upload-release-asset@v1  # 使用官方的upload-release-asset操作来上传发布资源
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布版本步骤中的上传URL
          asset_path: adblock_reject.srs  # 要上传的文件路径
          asset_name: adblock_reject.srs  # 上传后的文件名称
          asset_content_type: application/x-yaml  # 文件的内容类型




      - name: Upload adblock_reject.yaml  # 上传adblock_reject.yaml文件
        uses: actions/upload-release-asset@v1  # 使用官方的upload-release-asset操作来上传发布资源
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布版本步骤中的上传URL
          asset_path: adblock_reject.yaml  # 要上传的文件路径
          asset_name: adblock_reject.yaml  # 上传后的文件名称
          asset_content_type: application/x-yaml  # 文件的内容类型





      - name: Upload adblock_reject.txt  # 上传adblock_reject.txt文件
        uses: actions/upload-release-asset@v1  # 使用官方的upload-release-asset操作来上传发布资源
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布版本步骤中的上传URL
          asset_path: adblock_reject.txt  # 要上传的文件路径
          asset_name: adblock_reject.txt  # 上传后的文件名称
          asset_content_type: text/plain  # 文件的内容类型





      - name: Upload adblock_reject_change.txt  # 上传adblock_reject_change.txt文件
        uses: actions/upload-release-asset@v1  # 使用官方的upload-release-asset操作来上传发布资源
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布版本步骤中的上传URL
          asset_path: adblock_reject_change.txt  # 要上传的文件路径
          asset_name: adblock_reject_change.txt  # 上传后的文件名称
          asset_content_type: text/plain  # 文件的内容类型





      - name: Upload adblock_reject_change.yaml  # 上传adblock_reject_change.yaml文件
        uses: actions/upload-release-asset@v1  # 使用官方的upload-release-asset操作来上传发布资源
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 使用自定义的 TOKEN 进行身份验证
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用创建发布版本步骤中的上传URL
          asset_path: adblock_reject_change.yaml  # 要上传的文件路径
          asset_name: adblock_reject_change.yaml  # 上传后的文件名称
          
          
          
      

          
          
          
          
     
