name: Periodic Release

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有历史记录和标签

      - name: Get current time
        id: current-time
        run: echo "time=$(date +'%y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet HEAD@{20.minutes.ago} HEAD -- \
            adblock_reject.yaml \
            adblock_reject.txt \
            adblock_reject_change.yaml \
            adblock_reject_change.txt \
          || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.check_changes.outputs.changes == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.current-time.outputs.time }}
          release_name: Release ${{ steps.current-time.outputs.time }}
          draft: false
          prerelease: false

      - name: Upload adblock_reject.yaml
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject.yaml
          asset_name: adblock_reject.yaml
          asset_content_type: application/x-yaml

      - name: Upload adblock_reject.txt
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject.txt
          asset_name: adblock_reject.txt
          asset_content_type: text/plain

      - name: Upload adblock_reject_change.yaml
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_change.yaml
          asset_name: adblock_reject_change.yaml
          asset_content_type: application/x-yaml

      - name: Upload adblock_reject_change.txt
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_change.txt
          asset_name: adblock_reject_change.txt
          asset_content_type: text/plain
