name: Release AdBlock Files

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 保留手动触发选项

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Get current date
        id: date
        run: echo "date=Release-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.date }}
          release_name: ${{ env.date }}
          draft: false
          prerelease: false

      - name: Upload adblock_reject.yaml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject.yaml
          asset_name: adblock_reject.yaml
          asset_content_type: text/yaml

      - name: Upload adblock_reject.txt
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject.txt
          asset_name: adblock_reject.txt
          asset_content_type: text/plain

      - name: Upload adblock_reject_change.yaml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_change.yaml
          asset_name: adblock_reject_change.yaml
          asset_content_type: text/yaml

      - name: Upload adblock_reject_change.txt
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_change.txt
          asset_name: adblock_reject_change.txt
          asset_content_type: text/plain
