name: Repository security check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  security-scan:
    name: 安全扫描
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: 运行 Bandit
        run: bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}" -o bandit_results.txt || true

      - name: 运行 Safety
        run: safety check --full-report -o safety_results.txt || true

      - name: 上传扫描结果
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            bandit_results.txt
            safety_results.txt

      - name: 运行 CodeQL 分析
        uses: github/codeql-action/init@v2
        with:
          languages: python, javascript  # 根据你的仓库内容调整

      - name: 执行 CodeQL 分析
        uses: github/codeql-action/analyze@v2

      - name: 运行 Trivy 文件系统扫描
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: 上传 Trivy 扫描结果
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
