name: Run AdBlock Rule Generator_MRS  # 工作流名称

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 版本作为运行环境

    steps:
    - name: Setup Node.js 20  # 设置 Node.js 20 环境
      uses: actions/setup-node@v3  # 使用官方的 setup-node 操作来设置 Node.js 环境
      with:
        node-version: '20'  # 指定使用 Node.js 版本 20

    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v3  # 使用官方的 checkout 操作来检出代码

    - name: Install PowerShell  # 安装 PowerShell
      run: |
        sudo apt-get update  # 更新包列表
        sudo apt-get install -y wget apt-transport-https software-properties-common  # 安装必要的包
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb  # 下载微软的包配置文件
        sudo dpkg -i packages-microsoft-prod.deb  # 安装包配置文件
        sudo apt-get update  # 更新包列表
        sudo apt-get install -y powershell  # 安装 PowerShell
        rm packages-microsoft-prod.deb  # 删除包配置文件


    - name: Run adblock_rule_generator_mrs.ps1  # 运行adblock_rule_generator_mrs.ps1 脚本
      run: pwsh ./adblock_rule_generator_mrs.ps1  # 使用PowerShell运行脚本

    - name: Force Add and Commit MRS file  # 强制添加并提交 MRS 文件
      run: |
        git config --global user.name 'github-actions'  # 配置提交用户名
