name: 快速顺序执行工作流

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置工作流执行函数
        run: |
          function run_workflow() {
            local workflow_name="$1"
            echo "开始触发 $workflow_name 工作流"
            workflow_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | \
              jq -r ".workflows[] | select(.name==\"$workflow_name\") | .id")
            if [ -z "$workflow_id" ]; then
              echo "错误：未找到 $workflow_name 工作流"
              return 1
            fi
            echo "找到工作流 ID: $workflow_id"
            
            curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/dispatches" \
              -d '{"ref":"main"}'
            
            echo "等待工作流开始运行..."
            for i in {1..10}; do
              run_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch&status=in_progress" | \
                jq -r ".workflow_runs[] | select(.name==\"$workflow_name\") | .id" | head -n1)
              if [ -n "$run_id" ] && [ "$run_id" != "null" ]; then
                echo "工作流开始运行，ID: $run_id"
                break
              fi
              if [ $i -eq 10 ]; then
                echo "错误：工作流未在预期时间内开始运行"
                return 1
              fi
              sleep 3
            done
            
            echo "等待工作流完成..."
            while true; do
              status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id" | \
                jq -r '.status')
              if [ "$status" = "completed" ]; then
                echo "工作流 $workflow_name 已完成"
                return 0
              elif [ "$status" = "failure" ] || [ "$status" = "cancelled" ]; then
                echo "错误：工作流失败或被取消"
                return 1
              fi
              sleep 10
            done
          }

      - name: 运行 AdBlock Rule Generator_YAML
        run: run_workflow "Run AdBlock Rule Generator_YAML"

      - name: 运行 AdBlock Rule Generator_TXT
        run: run_workflow "Run AdBlock Rule Generator_TXT"

      - name: 运行 Process adblock list
        run: run_workflow "Process_adblock_list"

      - name: 运行 Release AdBlock Files
        run: run_workflow "Release AdBlock Files"
