name: 快速顺序执行工作流

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 jq
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g jq

      - name: 获取所有工作流 ID
        run: |
          workflows=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows")
          echo "YAML_ID=$(echo $workflows | jq '.workflows[] | select(.name=="Run AdBlock Rule Generator_YAML") | .id')" >> $GITHUB_ENV
          echo "TXT_ID=$(echo $workflows | jq '.workflows[] | select(.name=="Run AdBlock Rule Generator_TXT") | .id')" >> $GITHUB_ENV
          echo "PROCESS_ID=$(echo $workflows | jq '.workflows[] | select(.name=="Process_adblock_list") | .id')" >> $GITHUB_ENV
          echo "RELEASE_ID=$(echo $workflows | jq '.workflows[] | select(.name=="Release AdBlock Files") | .id')" >> $GITHUB_ENV

      - name: 触发所有工作流
        run: |
          trigger_workflow() {
            curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$1/dispatches" \
              -d '{"ref":"main"}'
          }
          trigger_workflow $YAML_ID &
          trigger_workflow $TXT_ID &
          trigger_workflow $PROCESS_ID &
          trigger_workflow $RELEASE_ID &
          wait

      - name: 等待工作流完成
        run: |
          check_workflow() {
            while true; do
              status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$1/runs?per_page=1" | \
                jq -r '.workflow_runs[0].status')
              if [ "$status" = "completed" ]; then
                break
              elif [ "$status" = "failure" ] || [ "$status" = "cancelled" ]; then
                echo "错误：工作流 $2 失败或被取消"
                exit 1
              fi
              sleep 10
            done
            echo "工作流 $2 已完成"
          }
          
          check_workflow $YAML_ID "AdBlock Rule Generator_YAML" &
          check_workflow $TXT_ID "AdBlock Rule Generator_TXT" &
          check_workflow $PROCESS_ID "Process adblock list" &
          check_workflow $RELEASE_ID "Release AdBlock Files" &
          wait
