name: Sequential Workflow Execution

on:
  workflow_dispatch:

jobs:
  run-sequentially:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run AdBlock Rule Generator (YAML)
        id: run_adblock_yaml
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Run AdBlock Rule Generator_YAML.yml',
              ref: context.ref
            });
            return {status: result.status};

      - name: Check Run AdBlock Rule Generator (YAML) Status
        if: steps.run_adblock_yaml.outputs.status != 'completed'
        run: exit 1

      - name: Run AdBlock Rule Generator (TXT)
        id: run_adblock_txt
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Run AdBlock Rule Generator_TXT.yml',
              ref: context.ref
            });
            return {status: result.status};

      - name: Check Run AdBlock Rule Generator (TXT) Status
        if: steps.run_adblock_txt.outputs.status != 'completed'
        run: exit 1

      - name: Process Adblock List
        id: process_adblock_list
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Process_adblock_list.yml',
              ref: context.ref
            });
            return {status: result.status};

      - name: Check Process Adblock List Status
        if: steps.process_adblock_list.outputs.status != 'completed'
        run: exit 1

      - name: Release AdBlock Files
        id: release_adblock_files
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Release AdBlock Files.yml',
              ref: context.ref
            });
            return {status: result.status};

      - name: Check Release AdBlock Files Status
        if: steps.release_adblock_files.outputs.status != 'completed'
        run: exit 1
