name: Sequential Workflow Execution

on:
  workflow_dispatch:

jobs:
  run-sequentially:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run AdBlock Rule Generator (YAML)
        id: run_adblock_yaml
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            try {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'Run_AdBlock_Rule_Generator_YAML.yml',
                ref: context.ref
              });
              return { status: 'success' };
            } catch (error) {
              core.setFailed(`Run AdBlock Rule Generator (YAML) failed: ${error.message}`);
              return { status: 'failed' };
            }

      - name: Check Run AdBlock Rule Generator (YAML) Status
        id: check_run_adblock_yaml
        run: exit 1
        if: steps.run_adblock_yaml.outputs.status == 'failed'

      - name: Run AdBlock Rule Generator (TXT)
        id: run_adblock_txt
        if: steps.run_adblock_yaml.outputs.status == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            try {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'Run_AdBlock_Rule_Generator_TXT.yml',
                ref: context.ref
              });
              return { status: 'success' };
            } catch (error) {
              core.setFailed(`Run AdBlock Rule Generator (TXT) failed: ${error.message}`);
              return { status: 'failed' };
            }

      - name: Check Run AdBlock Rule Generator (TXT) Status
        id: check_run_adblock_txt
        run: exit 1
        if: steps.run_adblock_txt.outputs.status == 'failed'

      - name: Process Adblock List
        id: process_adblock_list
        if: steps.run_adblock_txt.outputs.status == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            try {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'Process_adblock_list.yml',
                ref: context.ref
              });
              return { status: 'success' };
            } catch (error) {
              core.setFailed(`Process Adblock List failed: ${error.message}`);
              return { status: 'failed' };
            }

      - name: Check Process Adblock List Status
        id: check_process_adblock_list
        run: exit 1
        if: steps.process_adblock_list.outputs.status == 'failed'

      - name: Release AdBlock Files
        id: release_adblock_files
        if: steps.process_adblock_list.outputs.status == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            try {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'Release_AdBlock_Files.yml',
                ref: context.ref
              });
              return { status: 'success' };
            } catch (error) {
              core.setFailed(`Release AdBlock Files failed: ${error.message}`);
              return { status: 'failed' };
            }

      - name: Check Release AdBlock Files Status
        id: check_release_adblock_files
        run: exit 1
        if: steps.release_adblock_files.outputs.status == 'failed'
