name: Turn.txt to .mrs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy and rename adblock_reject.txt to adblock_reject.mrs
        run: cp adblock_reject.txt adblock_reject.mrs

      - name: Copy and rename adblock_reject_change.txt to adblock_reject_change.mrs
        run: cp adblock_reject_change.txt adblock_reject_change.mrs

      - name: Commit and push .mrs files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add adblock_reject.mrs adblock_reject_change.mrs
          git commit -m 'Add adblock_reject.mrs and adblock_reject_change.mrs files'
          git push
