name: Unzip mihomo.zip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Unzip mihomo.zip
      run: unzip -o mihomo.zip -d .
