name: Update and Convert Ruleset

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-and-convert:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and download mihomo v1.18.7
        shell: powershell
        run: |
          if (-not (Test-Path "./mihomo.exe")) {
            Write-Host "mihomo not found, downloading..."
            $url = "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.7/mihomo-windows-amd64-compatible-v1.18.7.zip"
            $zipFile = "mihomo.zip"
            $maxAttempts = 5
            $attempt = 1

            do {
              try {
                Write-Host "Downloading mihomo v1.18.7 (Attempt $attempt)..."
                Invoke-WebRequest -Uri $url -OutFile $zipFile -TimeoutSec 300
                if (Test-Path $zipFile) {
                  Write-Host "Download successful!"
                  Expand-Archive -Path $zipFile -DestinationPath . -Force
                  Remove-Item $zipFile
                  
                  $exeFile = Get-ChildItem -Recurse -Filter "*mihomo*.exe" | Select-Object -First 1
                  if ($exeFile) {
                    Rename-Item -Path $exeFile.FullName -NewName "mihomo.exe" -Force
                    Write-Host "Extraction and renaming complete!"
                    break
                  } else {
                    throw "Executable file not found in the extracted contents"
                  }
                }
              }
              catch {
                Write-Host "Download, extraction, or renaming failed. Error: $_"
                if ($attempt -eq $maxAttempts) {
                  Write-Host "Max attempts reached. Process failed."
                  exit 1
                }
                $attempt++
                Start-Sleep -Seconds 10
              }
            } while ($true)
          } else {
            Write-Host "mihomo already exists."
          }

      - name: Convert ruleset
        shell: powershell
        run: |
          Write-Host "Current directory:"
          Get-Location
          Write-Host "Directory contents:"
          Get-ChildItem
          Write-Host "Mihomo version:"
          & .\mihomo.exe -v
          Write-Host "Mihomo help:"
          & .\mihomo.exe convert-ruleset --help

          $maxAttempts = 5
          $attempt = 1
          do {
            try {
              Write-Host "Attempting conversion (Attempt $attempt)..."
              & .\mihomo.exe convert-ruleset domain yaml adblock_reject.yaml adblock_reject.mrs
              if ($LASTEXITCODE -ne 0) {
                throw "Conversion failed with exit code $LASTEXITCODE"
              }
              Write-Host "Conversion successful!"
              break
            }
            catch {
              Write-Host "Attempt $attempt failed. Error: $_"
              if ($attempt -eq $maxAttempts) {
                Write-Host "Max attempts reached. Exiting."
                exit 1
              }
              $attempt++
              Start-Sleep -Seconds 5
            }
          } while ($true)

      - name: Push changes
        shell: powershell
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          git add mihomo.exe
          git add adblock_reject.mrs
          
          $changes = git status --porcelain
          if ($changes) {
            git commit -m "Update mihomo.exe and adblock_reject.mrs"
            git push https://${env:TOKEN}@github.com/${env:GITHUB_REPOSITORY}.git HEAD:${env:GITHUB_REF}
            Write-Host "Changes committed and pushed."
          } else {
            Write-Host "No changes to commit."
          }
