# 工作流程名称
name: Update and Convert Ruleset

# 触发条件
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

# 定义作业
jobs:
  update-and-convert:
    runs-on: windows-latest  # 使用Windows运行环境
    steps:
      # 步骤1：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：检查并下载mihomo（如果需要）
      - name: Check and download mihomo v1.18.7 if needed
        shell: powershell
        run: |
# 检查根目录下是否已有mihomo.exe
if (Test-Path "./mihomo.exe") {
    Write-Host "mihomo.exe已存在，跳过下载步骤。"
} else {
    Write-Host "mihomo.exe不存在，请确保其在根目录下。"
    exit 1
}

# 这里可以继续添加其他逻辑


      # 步骤3：转换规则集
      - name: Convert ruleset
        shell: powershell
        run: |
          Write-Host "当前目录:"
          Get-Location
          Write-Host "目录内容:"
          Get-ChildItem
          Write-Host "Mihomo版本:"
          & .\mihomo.exe -v
          Write-Host "Mihomo帮助:"
          & .\mihomo.exe convert-ruleset --help

          # 尝试转换规则集，最多重试5次
          $maxAttempts = 5
          $attempt = 1
          do {
            try {
              Write-Host "正在尝试转换 (尝试 $attempt)..."
              # 执行mihomo转换命令
              & .\mihomo.exe convert-ruleset domain yaml adblock_reject.yaml adblock_reject.mrs
              if ($LASTEXITCODE -ne 0) {
                throw "转换失败，退出代码 $LASTEXITCODE"
              }
              Write-Host "转换成功！"
              break
            }
            catch {
              Write-Host "尝试 $attempt 失败。错误: $_"
              if ($attempt -eq $maxAttempts) {
                Write-Host "达到最大尝试次数。退出。"
                exit 1
              }
              $attempt++
              Start-Sleep -Seconds 5
            }
          } while ($true)

      # 步骤4：提交并推送更改
      - name: Push changes
        shell: powershell
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # 配置Git用户信息
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          # 添加mihomo.exe（如果是新下载的）和转换后的文件到Git
          git add -f mihomo.exe
          git add adblock_reject.mrs
          
          # 检查是否有更改需要提交
          $changes = git status --porcelain
          if ($changes) {
            # 如果有更改，进行提交和推送
            git commit -m "更新mihomo.exe（如果有变动）和adblock_reject.mrs"
            git push https://${env:TOKEN}@github.com/${env:GITHUB_REPOSITORY}.git HEAD:${env:GITHUB_REF}
            Write-Host "更改已提交并推送。"
          } else {
            Write-Host "没有需要提交的更改。"
          }
