# 工作流程名称
name: Update and Convert Ruleset

# 触发条件
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

# 定义作业
jobs:
  update-and-convert:
    runs-on: windows-latest  # 使用Windows运行环境
    steps:
      # 步骤1：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：检查并下载mihomo（如果需要）
      - name: Check and download mihomo v1.18.7 if needed
        shell: powershell
        run: |
          # 检查根目录下是否已有mihomo.exe
          if (Test-Path "./mihomo.exe") {
            Write-Host "mihomo.exe已存在，跳过下载步骤。"
          } else {
            Write-Host "mihomo未找到，开始下载..."
            $url = "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.7/mihomo-windows-amd64-compatible-v1.18.7.zip"
            $zipFile = "mihomo.zip"
            $maxAttempts = 5
            $attempt = 1

            # 尝试下载和解压，最多重试5次
            do {
              try {
                Write-Host "正在下载mihomo v1.18.7 (尝试 $attempt)..."
                Invoke-WebRequest -Uri $url -OutFile $zipFile
                Write-Host "下载完成，正在解压..."
                Expand-Archive -Path $zipFile -DestinationPath . -Force
                Write-Host "解压完成。"
                Remove-Item -Path $zipFile
                break
              } catch {
                Write-Host "下载或解压失败: $_"
                $attempt++
                if ($attempt -gt $maxAttempts) {
                  Write-Host "达到最大重试次数，退出。"
                  exit 1
                }
                Start-Sleep -Seconds 10
              }
            } while ($true)
          }

      # 步骤3：转换规则集
      - name: Convert ruleset
        shell: powershell
        run: |
          ./mihomo convert-ruleset domain/ipcidr yaml adblock_reject.yaml adblock_reject.mrs

      # 步骤4：提交转换后的文件
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'adblock_reject.mrs'
          message: 'Update adblock_reject.mrs'
          author_name: 'github-actions'
          author_email: 'github-actions@users.noreply.github.com'
