# 工作流程名称
name: Update and Convert Ruleset

# 触发条件
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

# 定义作业
jobs:
  update-and-convert:
    runs-on: windows-latest  # 使用 Windows 运行环境
    steps:
      # 步骤1：检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 步骤2：检查是否存在 mihomo
      - name: Check for mihomo
        shell: powershell
        run: |
          if (-not (Test-Path "./mihomo/mihomo.exe")) {
            Write-Host "mihomo not found, downloading..."
            $url = "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.7/mihomo-windows-amd64-compatible-v1.18.7.zip"
            $zipFile = "mihomo.zip"
            
            # 下载并解压 mihomo
            Invoke-WebRequest -Uri $url -OutFile $zipFile -TimeoutSec 300
            Expand-Archive -Path $zipFile -DestinationPath . -Force
            
            # 移动 mihomo 到根目录
            Move-Item -Path "./mihomo-windows-amd64-compatible-v1.18.7/mihomo.exe" -Destination "./mihomo/mihomo.exe"
            
            # 清理临时文件
            Remove-Item $zipFile
            Remove-Item -Recurse -Force "./mihomo-windows-amd64-compatible-v1.18.7"
          } else {
            Write-Host "mihomo already exists."
          }

      # 步骤3：执行 mihomo 指令
      - name: Convert ruleset with mihomo
        shell: powershell
        run: |
          .\mihomo\mihomo.exe convert-ruleset domain/ipcidr yaml adblock_reject.yaml adblock_reject.mrs

      # 步骤4：推送生成的文件到根目录
      - name: Commit and push adblock_reject.mrs
        uses: EndBug/add-and-commit@v9
        with:
          add: 'adblock_reject.mrs'
          message: 'Update adblock_reject.mrs'
