name: Update and Convert Ruleset

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-and-convert:
    runs-on: windows-latest  # 使用 Windows 运行环境
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and extract mihomo v1.18.7
        shell: powershell
        run: |
          $url = "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.7/mihomo-windows-amd64-compatible-v1.18.7.zip"
          $zipFile = "mihomo.zip"
          $maxAttempts = 5
          $attempt = 1

          do {
            try {
              Write-Host "Downloading mihomo v1.18.7 (Attempt $attempt)..."
              Invoke-WebRequest -Uri $url -OutFile $zipFile -TimeoutSec 300
              if (Test-Path $zipFile) {
                Write-Host "Download successful!"
                Expand-Archive -Path $zipFile -DestinationPath . -Force
                Remove-Item $zipFile
                Rename-Item -Path "mihomo-windows-amd64.exe" -NewName "mihomo.exe" -Force
                Write-Host "Extraction complete!"
                break
              }
            }
            catch {
              Write-Host "Download or extraction failed. Error: $_"
              if ($attempt -eq $maxAttempts) {
                Write-Host "Max attempts reached. Download failed."
                exit 1
              }
              $attempt++
              Start-Sleep -Seconds 10
            }
          } while ($true)

          Get-ChildItem  # 列出当前目录内容

      - name: Convert ruleset
        shell: powershell
        run: |
          Write-Host "Current directory:"
          Get-Location
          Write-Host "Directory contents:"
          Get-ChildItem
          $maxAttempts = 5
          $attempt = 1
          do {
            try {
              & .\mihomo.exe convert-ruleset domain/ipcidr yaml adblock_reject.yaml adblock_reject.mrs
              Write-Host "Conversion successful!"
              break
            }
            catch {
              Write-Host "Attempt $attempt failed. Error: $_"
              if ($attempt -eq $maxAttempts) {
                Write-Host "Max attempts reached. Exiting."
                exit 1
              }
              $attempt++
              Start-Sleep -Seconds 5
            }
          } while ($true)

      - name: Push changes
        shell: powershell
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add adblock_reject.mrs
          git commit -m "Update adblock_reject.mrs" -ErrorAction SilentlyContinue
          if ($LASTEXITCODE -eq 0) {
            git push https://${env:TOKEN}@github.com/${env:GITHUB_REPOSITORY}.git HEAD:${env:GITHUB_REF}
          } else {
            Write-Host "No changes to commit"
          }
